[build]
  publish = "dist"
  functions = "server/functions"

[[redirects]]
  # Redirect all API requests to the Netlify function
  from = "/project/*"
  to = "/.netlify/functions/routes/project"
  status = 200

[[headers]]
 # Add CORS headers to the API
  for = "/.netlify/functions/routes/project/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, DELETE, PATCH"  # Add PATCH method
    Access-Control-Allow-Headers = "Content-Type"
